DROP TABLE IF EXISTS addmovies;

CREATE TABLE IF NOT EXISTS addmovies(
id SERIAL PRIMARY KEY,
title VARCHAR(2000),
release_date VARCHAR(2000),
poster_path VARCHAR(2000),
overview VARCHAR(2000),
comments VARCHAR(2000)
);